services:
  producer:
    volumes:
      - ./:/src/
      - ~/.nuget/packages:/root/.nuget/packages:ro
    env_file:
      - ./.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Host=postgres;Port=5432;Database=${POSTGRES_DB};
    depends_on:
      - rabbitmq
    command: >
      sh -c "dotnet watch --project /src run --urls=http://0.0.0.0:8080"
    ports:
      - 5000:8080
  
  consumer:
    volumes:
      - ./:/src/
      - ~/.nuget/packages:/root/.nuget/packages:ro
    depends_on:
      - rabbitmq
      - producer
    command: >
      sh -c "dotnet watch --project /src run --urls=http://0.0.0.0:8080"
    ports:
      - 5001:8080
  
  rabbitmq:
    container_name: rabbitmq-user-manager
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    networks:
      user-manager-networks:
        aliases:
          - "rabbitmq"
  
  db:
    container_name: postgres-user-manager
    image: postgres:17
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      user-manager-networks:
        aliases:
            - "postgres"
volumes:
  dbdata: